spring:
  application:
    name: IssueFlow
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  # jpa:
  #   hibernate:
  #     ddl-auto: update
logging:
  level:
    org.springframework.boot: WARN
    org.hibernate: WARN
cors:
  origins: ${ALLOWED_ORIGINS:http://localhost:5173}
#  level:
#    org:
#      springframework:
#        security: DEBUG
